---
settings:
  name: Software updates
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documents sur les mises à jour logicielles
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: ontap
  - section: support
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: Netapp Console
  repo: console-family
